version: '3.8'

service: 
  node-app:
     build: .
     container_name: node-container
     ports:
       - "3000:3000"
     volumes:
       - .:/app
       - /app/node_modules
     environment:
       - Node_ENV=development
     restart: always
   
